Discord:
  Token: ""
  SupportGuildInvite: ""
  MYGGuildID: ""
  ReportChannelID: ""
  LogChannelID: ""
  ProjectLeaderID: ""
  ActivityType: "WATCHING"
  Activity: "Code"
  DefaultEmbed:
    Color: 0x7c3aed
    Footer: "MatchYourGame | Project in development"
SQL:
  JDBC: "jdbc:mysql://localhost:3306/matchyourgame?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
  Username: "root"
  Password: ""

GameAPIs:
  OAuth:
    BindAddress: "127.0.0.1"
    CallbackPort: 8080
    RedirectUri: "https://auth.matchyourgame.net/oauth2/riot-games"
  Valorant:
    ApiKey: "RGAPI-6c8cd190-84d1-47fe-821e-fecb4adca7b4"
    RsoClientId: ""
    RsoClientSecret: ""
    RsoRouting: "europe"

CreatedUserToBecomePartnerGuild: 30
PartnerGuildUserCreations: 30

Testing:
  RoleID: 1438288753822007367
  Enabled: true
