Discord:
  Token: ""
  SupportGuildInvite: ""
  MYGGuildID: ""
  ReportChannelID: ""
  LogChannelID: ""
  ProjectLeaderID: ""
  ActivityType: "WATCHING"
  Activity: "Code"
  DefaultEmbed:
    Color: 0x7c3aed
    Footer: "MatchYourGame | Project in development"
SQL:
  JDBC: "jdbc:mysql://localhost:3306/matchyourgame?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
  Username: "root"
  Password: ""

CreatedUserToBecomePartnerGuild: 30
PartnerGuildUserCreations: 30

Testing:
  RoleID: 1438288753822007367
  Enabled: true
